<?php
/**
 * Admin class - React-powered admin panel
 *
 * @package Nginx_Opcache_Manager
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class to handle admin pages and settings
 */
class Nginx_Opcache_Manager_Admin {

	/**
	 * Constructor
	 */
	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_admin_menu' ) );
		add_action( 'admin_init', array( $this, 'register_settings' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
		add_action( 'wp_dashboard_setup', array( $this, 'add_dashboard_widget' ) );

		// Schedule background stats recording
		if ( ! wp_next_scheduled( 'nom_record_stats' ) ) {
			wp_schedule_event( time(), 'hourly', 'nom_record_stats' );
		}
		add_action( 'nom_record_stats', array( $this, 'record_background_stats' ) );
	}

	/**
	 * Add admin menu
	 */
	public function add_admin_menu() {
		add_menu_page(
			__( 'Nginx Opcache Manager', 'nginx-opcache-manager' ),
			__( 'Cache Manager', 'nginx-opcache-manager' ),
			'manage_options',
			'nginx-opcache-manager',
			array( $this, 'admin_page' ),
			'dashicons-shield',
			75
		);

		add_submenu_page(
			'nginx-opcache-manager',
			__( 'Dashboard', 'nginx-opcache-manager' ),
			__( 'Dashboard', 'nginx-opcache-manager' ),
			'manage_options',
			'nginx-opcache-manager',
			array( $this, 'admin_page' )
		);

		add_submenu_page(
			'nginx-opcache-manager',
			__( 'Analytics', 'nginx-opcache-manager' ),
			__( 'Analytics', 'nginx-opcache-manager' ),
			'manage_options',
			'nginx-opcache-manager-analytics',
			array( $this, 'analytics_page' )
		);

		add_submenu_page(
			'nginx-opcache-manager',
			__( 'Settings', 'nginx-opcache-manager' ),
			__( 'Settings', 'nginx-opcache-manager' ),
			'manage_options',
			'nginx-opcache-manager-settings',
			array( $this, 'settings_page' )
		);
	}

	/**
	 * Register plugin settings
	 */
	public function register_settings() {
		register_setting( 'nom_settings_group', 'nom_nginx_cache_enabled' );
		register_setting( 'nom_settings_group', 'nom_nginx_cache_path' );
		register_setting( 'nom_settings_group', 'nom_enable_notifications' );
		register_setting( 'nom_settings_group', 'nom_enable_post_cache_flush' );
		register_setting( 'nom_settings_group', 'nom_enable_woocommerce_flush', array( 'sanitize_callback' => array( $this, 'sanitize_checkbox' ) ) );
		register_setting( 'nom_settings_group', 'nom_fastcgi_cache_key_schema' );
		register_setting(
			'nom_settings_group',
			'nom_schedule_enabled',
			array( 'sanitize_callback' => array( $this, 'sanitize_checkbox' ) )
		);
		register_setting(
			'nom_settings_group',
			'nom_schedule_interval',
			array( 'sanitize_callback' => array( 'Nginx_Opcache_Manager_Scheduler', 'sanitize_interval' ) )
		);
		register_setting(
			'nom_settings_group',
			'nom_schedule_targets',
			array( 'sanitize_callback' => array( 'Nginx_Opcache_Manager_Scheduler', 'sanitize_targets' ) )
		);
	}

	/**
	 * Enqueue admin scripts and styles
	 */
	public function enqueue_scripts( $hook ) {
		if ( strpos( $hook, 'nginx-opcache-manager' ) === false ) {
			return;
		}

		// Enqueue React admin build
		$build_file    = NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'build/index.js';
		$asset_file    = NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'build/index.asset.php';
		$style_file    = NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'build/index.css';

		if ( file_exists( $build_file ) ) {
			// Read dependencies from asset file generated by @wordpress/scripts
			$dependencies = array( 'react', 'react-dom' );
			$version      = NGINX_OPCACHE_MANAGER_VERSION;

			if ( file_exists( $asset_file ) ) {
				$asset_data  = require $asset_file;
				$dependencies = $asset_data['dependencies'] ?? $dependencies;
				$version      = $asset_data['version'] ?? $version;
			}

			wp_enqueue_script(
				'nom-react-admin',
				NGINX_OPCACHE_MANAGER_PLUGIN_URL . 'build/index.js',
				$dependencies,
				$version,
				true
			);

			wp_set_script_translations( 'nom-react-admin', 'nginx-opcache-manager' );

			wp_localize_script( 'nom-react-admin', 'nomData', array(
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
				'pluginUrl' => NGINX_OPCACHE_MANAGER_PLUGIN_URL,
				'restUrl'   => rest_url( 'nom/v1/' ),
			) );
		}

		if ( file_exists( $style_file ) ) {
			wp_enqueue_style(
				'nom-react-admin',
				NGINX_OPCACHE_MANAGER_PLUGIN_URL . 'build/index.css',
				array(),
				NGINX_OPCACHE_MANAGER_VERSION
			);
		}
	}

	/**
	 * Main admin page - React powered
	 */
	public function admin_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Unauthorized', 'nginx-opcache-manager' ) );
		}

		include NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'admin/views/react-dashboard.php';
	}

	/**
	 * Analytics page - React powered
	 */
	public function analytics_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Unauthorized', 'nginx-opcache-manager' ) );
		}

		include NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'admin/views/react-dashboard.php';
	}

	/**
	 * Settings page - React powered
	 */
	public function settings_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Unauthorized', 'nginx-opcache-manager' ) );
		}

		include NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'admin/views/react-dashboard.php';
	}

	/**
	 * Sanitize checkbox value to 0/1.
	 *
	 * @param mixed $value Raw value.
	 * @return int
	 */
	public function sanitize_checkbox( $value ) {
		return $value ? 1 : 0;
	}

	/**
	 * Add dashboard widget
	 */
	public function add_dashboard_widget() {
		wp_add_dashboard_widget( 'nom_dashboard_widget', __( 'Cache Status', 'nginx-opcache-manager' ), array( $this, 'dashboard_widget' ) );
	}

	/**
	 * Dashboard widget output
	 */
	public function dashboard_widget() {
		include NGINX_OPCACHE_MANAGER_PLUGIN_DIR . 'admin/views/dashboard-widget.php';
	}

	/**
	 * Record statistics in background
	 */
	public function record_background_stats() {
		$stats = new Nginx_Opcache_Manager_Stats();
		$stats->record_stats();
	}
}
